[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/skel84/corust"

[workspace.dependencies]
coroot-rs = { path = "crates/coroot-rs", version = "0.1.0" }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tokio = { version = "1", default-features = false }
url = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true
